from base import *

INSTALLED_APPS += [
    "geo",
    "cities_light"
]

CITIES_LIGHT_APP_NAME = 'geo'
CITIES_LIGHT_TRANSLATION_LANGUAGES = ['en', ]
CITIES_LIGHT_INCLUDE_COUNTRIES = ['NG', ]
CITIES_LIGHT_INCLUDE_CITY_TYPES = ['PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLC', 'PPLF', 'PPLG', 'PPLL', 'PPLR', 'PPLS', 'STLMT',]
